name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Pages
    # Add these permissions
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        # We run the build script manually here. The action only handles the deploy.
        # This should be the script in your package.json that runs 'next build && npx @cloudflare/next-on-pages'
        run: npm run build:cf
        env:
          # You can add build-time environment variables here if needed
          NODE_VERSION: '24'

      - name: Publish to Cloudflare Pages
        # This is the new, correct action for deploying to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'leongkarwan' # The name of your project in the Cloudflare dashboard
          directory: '.vercel/output/static' # The directory of your build assets
          gitHubToken: ${{ secrets.GITHUB_TOKEN }} # Optional: for Deployments integration

# name: Deploy to Cloudflare Workers
# on:
#   push:
#     branches:
#       - main # The branch to deploy from, change if you use 'master' or another name
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     name: Deploy
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: '24' # Use a Node.js version compatible with your project
#       - name: Install Dependencies
#         run: npm install
#       - name: Publish to Cloudflare Workers
#         uses: cloudflare/wrangler-action@v3
#         with:
#           apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
#           accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
#           # The 'wrangler deploy' command is run by default
